# Generated by Django 2.1.10 on 2020-11-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=250)),
                ('departure_city', models.CharField(max_length=250)),
                ('departure_time', models.IntegerField(max_length=250)),
                ('arrival_city', models.CharField(max_length=250)),
                ('arrival_time', models.IntegerField(max_length=250)),
            ],
        ),
    ]
