# Generated by Django 2.1.10 on 2020-12-10 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.IntegerField(),
        ),
    ]
